### ISSUE TITLE
Question: i got a decode error when i'm using `GetAccountInfo` function to get candymachinev2 state info

### ISSUE THREAD

**Issue by godtoy** [gagliardetto/metaplex-go#15]
in exmaple test file
![image](https://user-images.githubusercontent.com/13638996/165316316-a0a55ac6-fd9e-47ec-adbc-9eaca7435686.png)

![image](https://user-images.githubusercontent.com/13638996/165316266-8dd5d4e9-8803-4d5b-91b7-a505861d7f13.png)

Many thanks. Could u help me or tell me how to fix this errors?

**Comment by godtoy** [comment]
I'm very interested in your repos built recently for SOLANA, hope i can join you one day.

**Comment by gagliardetto** [comment]
hey @godtoy 

The data contained in the account you're fetching is not a `CandyMachine`.

**Comment by gagliardetto** [comment]
Each type of account contains a special 8 bytes at the beginning that determine its type (so that one account type won't be accidentally parsed as another).

The `CandyMachine` object expects an account that starts with these first 8 bytes: `[51, 173, 177, 113, 25, 241, 109, 189]`

That's not the case here, which means it's not a `CandyMachine`.

**Comment by godtoy** [comment]
I figure out why,haha. it's different with CandyMachineV2 IDL

https://explorer.solana.com/address/CMZYPASGWeTz7RNGHaRJfCq2XQ5pYK6nDvVQxzkH51zb/anchor-program

I solved , thank you so much

**Comment by godtoy** [comment]
it's from magiceden, https://magiceden.io/ . could u please add it in this project?

**Comment by godtoy** [comment]
anchor-go is  also so amazing

**Comment by godtoy** [comment]
Same with Candymachine, it just a fork less change.
https://explorer.solana.com/address/CMZYPASGWeTz7RNGHaRJfCq2XQ5pYK6nDvVQxzkH51zb/anchor-program

U can copy this IDL json config to your `anchor-go` project than gen it to metaplex folder

**Comment by godtoy** [comment]
![image](https://user-images.githubusercontent.com/13638996/165322498-1fa25d9d-87c1-4ea3-a597-8a047ed57f47.png)

works for me now.

**Comment by godtoy** [comment]
![image](https://user-images.githubusercontent.com/13638996/165322606-26a16cea-e2ed-4fdd-8480-d6fd06267db1.png)
