### ISSUE TITLE
How to mint new edition from master edition via token

### ISSUE THREAD

**Issue by johnbailon** [gagliardetto/metaplex-go#2]
Hello, first of all, thanks for working on this. Very helpful in learning Solana/Metaplex as a Go dev. Kudos.
Hoping to get some help on this, I'm trying to mint a new edition from an existing master edition to a new address and I'm hitting this error:

```
Program 11111111111111111111111111111111 invoke [1]
Program 11111111111111111111111111111111 success
Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]
Program log: Instruction: InitializeMint
Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2390 of 200000 compute units
Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL invoke [1]
Program log: Transfer 2039280 lamports to the associated token account
Program 11111111111111111111111111111111 invoke [2]
Program 11111111111111111111111111111111 success
Program log: Allocate space for the associated token account
Program 11111111111111111111111111111111 invoke [2]
Program 11111111111111111111111111111111 success
Program log: Assign the associated token account to the SPL Token program
Program 11111111111111111111111111111111 invoke [2]
Program 11111111111111111111111111111111 success
Program log: Initialize the associated token account
Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]
Program log: Instruction: InitializeAccount
Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 3449 of 179470 compute units
Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL consumed 24660 of 200000 compute units
Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL success
Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]
Program log: Instruction: MintTo
Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2879 of 200000 compute units
Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s invoke [1]
Program log: Instruction: Mint New Edition from Master Edition Via Token
Program log: Incorrect account owner
Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s consumed 5204 of 200000 compute units
Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s failed: custom program error: 0x39"
```

This is how I am doing it:
`payer` is `solana.privateKey` of account that created and has the master edition
`withdrawalAddress` is account to send the new edition to
`masterMint` is the public key of the NFT

1. generated new keypair called `newMintAccount`
2. created token account: mint auth and freeze auth are `payer.PublicKey()`, mint account is `newMintAccount.PublicKey()`
3. created associated token account: wallet is `withdrawalAddress`, mint is `newMintAccount`
4. `associatedTokenAddress` is found via `solana.FindAssociatedTokenAddress()` using `withdrawalAddress` and `newMintAccount.PublicKey()`
5. MintTo instruction: amount `1`, mint account is `newMintAccount.PublicKey()`, destination account is `associatedTokenAddress` and auth account is `payer.PublicKey()`
6. `newMetadataKey` is found via:
```golang
newMetadataKey, _, err := solana.FindProgramAddress(
		[][]byte{
			[]byte(token_metadata.PREFIX),
			solana.TokenMetadataProgramID.Bytes(),
			newMintAccount.PublicKey().Bytes(),
		},
		solana.TokenMetadataProgramID,
	)
```

7. `newEditionPDA` is found via:
```golang
newEditionPDA, _, err := solana.FindProgramAddress(
		[][]byte{
			[]byte(token_metadata.PREFIX),
			solana.TokenMetadataProgramID.Bytes(),
			newMintAccount.PublicKey().Bytes(),
			[]byte(token_metadata.EDITION),
		},
		solana.TokenMetadataProgramID,
	)
```

8. `masterRecordMetadata` is found via:
```golang
masterRecordMetadata, _, err := solana.FindProgramAddress(
	[][]byte{
		[]byte(token_metadata.PREFIX),
		solana.TokenMetadataProgramID.Bytes(),
		masterMint.Bytes(),
	},
	solana.TokenMetadataProgramID,
)
```

9. `masterRecordEditionV2PDA` is found via:
```golang
masterRecordEditionV2PDA, _, err := solana.FindProgramAddress(
	[][]byte{
		[]byte(token_metadata.PREFIX),
		solana.TokenMetadataProgramID.Bytes(),
		masterRecordMetadata.Bytes(),
		[]byte(token_metadata.EDITION),
	},
	solana.TokenMetadataProgramID,
)
```

10. `editionPDA` is found via:
```golang
edition := uint64(1)
x := math.Floor(float64(edition) / token_metadata.EDITION_MARKER_BIT_SIZE)
b := make([]byte, 8)
binary.LittleEndian.PutUint64(b, math.Float64bits(x))
editionPDA, _, err := solana.FindProgramAddress(
		[][]byte{
			[]byte(token_metadata.PREFIX),
			solana.TokenMetadataProgramID.Bytes(),
			masterRecordMetadata.Bytes(),
			[]byte(token_metadata.EDITION),
			b,
		},
		solana.TokenMetadataProgramID,
	)
```

11. `tokenAccountOfMasterMint` is found via:
```golang
tokenAccountOfMasterMint, _, err := solana.FindAssociatedTokenAddress(
	payer.PublicKey(),
	masterMint,
)
```

12. Finally, this is the instruction for minting a new edition:
```golang
printEditionInstruction := token_metadata.NewMintNewEditionFromMasterEditionViaTokenInstructionBuilder().
	SetArgs(token_metadata.MintNewEditionFromMasterEditionViaTokenArgs{Edition: edition}).
	SetNewMetadataKeyAccount(newMetadataKey). // pda from token_metadata.PREFIX, solana.TokenMetadataProgramID, newMintAccount.PublicKey()
	SetNewEditionPDAAccount(newEditionPDA).
	SetMasterRecordEditionV2Account(masterRecordEditionV2PDA).
	SetMintOfNewTokenAccount(newMintAccount.PublicKey()).
	SetEditionPDAAccount(editionPDA).
	SetMintAuthorityAccount(payer.PublicKey()).
	SetPayerAccount(payer.PublicKey()).
	SetOwnerOfTokenAccount(payer.PublicKey()).
	SetTokenAccount(tokenAccountOfMasterMint).
	SetUpdateAuthorityInfoAccount(payer.PublicKey()).
	SetMasterRecordMetadataAccount(masterRecordMetadata).
	SetTokenProgramAccount(solana.TokenProgramID).
	SetSystemProgramAccount(solana.SystemProgramID).
	SetRentInfoAccount(solana.SysVarRentPubkey)
```

**Comment by gagliardetto** [comment]
Hi

I'm looking into this, and one thing I found is the point `10.` might not be matching this: https://github.com/metaplex-foundation/metaplex/blob/f3366f3ab09e9900407f10856659edab6c631fc0/js/packages/common/src/actions/metadata.ts#L1202

(i.e. the editionNumber, which is the last item in the seeds slice, which should be a string converted to a byte slice).

But that's probably no the issue that causes the error. Will update you.

**Comment by gagliardetto** [comment]
`MintNewEditionFromMasterEditionViaToken` instruction processing: https://github.com/metaplex-foundation/metaplex/blob/397f488935f2075b0798946c30cf5f7b0ddcd3f0/rust/token-metadata/program/src/utils.rs#L912-L1030

Example instruction usage:

1. https://github.com/metaplex-foundation/metaplex/blob/397f488935f2075b0798946c30cf5f7b0ddcd3f0/rust/token-metadata/program/src/instruction.rs#L380-L434


2. https://github.com/metaplex-foundation/metaplex/blob/397f488935f2075b0798946c30cf5f7b0ddcd3f0/rust/token-metadata/program/tests/mint_new_edition_from_master_edition_via_token.rs#L133-L152

3. https://github.com/metaplex-foundation/metaplex/blob/397f488935f2075b0798946c30cf5f7b0ddcd3f0/rust/token-metadata/program/tests/utils/edition_marker.rs#L170-L189

4. https://github.com/metaplex-foundation/metaplex/blob/0ba4954762c8ad7a7802cbb03268fce5de932b40/js/packages/web/src/actions/setupMintEditionIntoWalletInstructions.ts#L13-L58

**Comment by gagliardetto** [comment]
When you see a `incorrect account owner`, it might also mean that the account doesn't exist (yeah, that's very cryptic).

**Comment by gagliardetto** [comment]
Awesome! Thanks for the summary of how you solved the issue!
