### ISSUE TITLE
Support off-chain metadata

### ISSUE THREAD

**Issue by terorie** [gagliardetto/metaplex-go#3]
As far as I can tell, this repo so far only supports decoding on-chain account data and instructions. 

The Metaplex standard also describes how to store off-chain NFT data on the Internet (mostly on Arweave) https://docs.metaplex.com/nft-standard#uri-json-schema

It would be useful to add structs matching the off-chain data to this repo, and maybe a hardened HTTP client for fetching off-chain data from untrusted servers.

**Comment by gagliardetto** [comment]
Hey @terorie 

Do you want a copy of the meta I downloaded? I can send it to you. It's about 1M records (if I remember correctly)

**Comment by terorie** [comment]
@gagliardetto That's brilliant, yes please. Would you mind uploading it to archive.org? Researchers also love this sort of NFT data btw.

**Comment by gagliardetto** [comment]
I don't know about archive.org, but here's a repo: https://github.com/gagliardetto/solana-meta-snap-15oct2021

**Comment by gagliardetto** [comment]
Closing
