### ISSUE TITLE
Minting

### ISSUE THREAD

**Issue by sparkycj328** [gagliardetto/metaplex-go#8]
How would one go about minting, only using code, from an already deployed program after following along to the example?

**Comment by gagliardetto** [comment]
The example is incomplete/wrong (I'll eventually rewrite it)

The best would be to look directly at the rust code.

Always remember that candy machine v1 is deprecated and that you must use `v2`.

**Comment by sparkycj328** [comment]
I am taking a look at the generated bindings in the MintNft.go file under the candy machine v2 folder, what role does the creator bumb variable play, how do i find more documentation on it
