### ISSUE TITLE
Unable to decode instruction

### ISSUE THREAD

**Issue by sparkycj328** [gagliardetto/metaplex-go#9]

**Comment by gagliardetto** [comment]
Did you call `candy_machinev2.SetProgramID(candyMachineProgramID)`?

Something like this (but for v2): https://github.com/gagliardetto/metaplex-go/blob/5814aedc5ee8a0d679ddd0354d70c51cd73c4427/examples/candy/main.go#L111-L114

**Comment by gagliardetto** [comment]
You can call the `SetProgramID` func just once. Make sure it's not called somewhere else.
